services:
  app:
    build: ./ass1
    ports:
      - "80:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
    volumes:
      - ./ass1:/app
      - /app/node_modules
    command: npm run dev

  api:
    build: ./api
    ports:
      - "4080:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/my_db
    volumes:
      - ./api:/app
      - /app/node_modules
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
